# Generated by Django 5.1.6 on 2025-03-28 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='persona',
            unique_together={('pais', 'nickname')},
        ),
        migrations.AddConstraint(
            model_name='persona',
            constraint=models.CheckConstraint(condition=models.Q(('edad__gte', 18)), name='edad_minima'),
        ),
    ]
