# Generated by Django 5.1.6 on 2025-04-02 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('nacionalidad', models.CharField(max_length=30)),
                ('edad', models.PositiveIntegerField(default=0)),
                ('seudonimo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Seudónimo')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos')),
            ],
            options={
                'verbose_name': 'Catálogo de Autores',
                'verbose_name_plural': 'Catálogo de Autores',
                'ordering': ['nombre'],
            },
        ),
    ]
