# Generated by Django 5.1.6 on 2025-04-03 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='reseña',
            field=models.TextField(blank=True, null=True),
        ),
    ]
