# Generated by Django 5.1.6 on 2025-03-13 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autor', '0002_alter_autor_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'ordering': ['nombre'], 'verbose_name': 'Catálogo de Autor', 'verbose_name_plural': 'Catálogo de Autores'},
        ),
    ]
