# Generated by Django 5.1.6 on 2025-09-01 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autor', '0002_autor_reseña'),
        ('autor', '0003_alter_autor_options'),
    ]

    operations = [
    ]
