# Generated by Django 5.1.6 on 2025-09-01 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autor', '0004_merge_0002_autor_reseña_0003_alter_autor_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'ordering': ['nombre'], 'verbose_name': 'Catálogo de Autores', 'verbose_name_plural': 'Catálogo de Autores'},
        ),
    ]
