# Generated by Django 5.1.6 on 2025-09-14 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autor', '0005_alter_autor_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_autor/'),
        ),
    ]
