# Generated by Django 5.1.6 on 2025-04-02 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('libro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('nacionalidad', models.CharField(max_length=30)),
                ('edad', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Catálogo de Lector',
                'verbose_name_plural': 'Catálogo de Lectores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateField(verbose_name='Fecha de prestamo')),
                ('fecha_devolucion', models.DateField(blank=True, null=True, verbose_name='Fecha de devolucion')),
                ('devuelto', models.BooleanField(default=False)),
                ('lector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lector.lector')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='libro_prestamo', to='libro.libro')),
            ],
            options={
                'verbose_name': 'Control de Prestamos',
                'verbose_name_plural': 'Control de Prestamos',
                'ordering': ['fecha_prestamo'],
            },
        ),
    ]
