# Generated by Django 5.1.6 on 2025-03-13 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lector', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lector',
            options={'ordering': ['nombre'], 'verbose_name': 'Catálogo de Lector', 'verbose_name_plural': 'Catálogo de Lectores'},
        ),
        migrations.AlterModelOptions(
            name='prestamo',
            options={'ordering': ['fecha_prestamo'], 'verbose_name': 'Control de Prestamos', 'verbose_name_plural': 'Control de Prestamos'},
        ),
    ]
