# Generated by Django 5.1.6 on 2025-08-08 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lector', '0002_prestamo_vencimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='lector',
            name='telefono',
            field=models.CharField(default=646553322, max_length=15),
            preserve_default=False,
        ),
    ]
