# Generated by Django 5.1.6 on 2025-09-01 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lector', '0002_alter_lector_options_alter_prestamo_options'),
        ('lector', '0003_lector_telefono'),
    ]

    operations = [
    ]
