# Generated by Django 5.1.6 on 2025-04-02 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Lista de categoria',
                'verbose_name_plural': 'Lista de categorias',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('fecha_publicacion', models.DateField(verbose_name='Fecha de publicacion')),
                ('portada', models.ImageField(upload_to='portadas')),
                ('visitas', models.PositiveIntegerField(default=0)),
                ('autores', models.ManyToManyField(to='autor.autor')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoria_libro', to='libro.categoria')),
            ],
            options={
                'verbose_name': 'Catálogo de Libro',
                'verbose_name_plural': 'Catálogo de Libros',
                'ordering': ['titulo'],
            },
        ),
    ]
