# Generated by Django 5.1.6 on 2025-04-10 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0002_libro_sinopsis'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
