# Generated by Django 5.1.6 on 2025-04-10 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0003_libro_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='stock',
            field=models.PositiveIntegerField(),
        ),
    ]
