# Generated by Django 5.1.6 on 2025-09-01 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0003_alter_categoria_options_alter_libro_categoria'),
        ('libro', '0005_alter_libro_stock'),
    ]

    operations = [
    ]
