# Generated by Django 5.1.6 on 2025-09-14 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0006_merge_20250901_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='portadas_libros/'),
        ),
    ]
