# Generated by Django 5.1.6 on 2025-09-15 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0008_alter_libro_portada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='portadas'),
        ),
    ]
